apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-operator
  labels:
    app: custom-operator
spec:
  selector:
    matchLabels:
      app: custom-operator
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: custom-operator
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
        - name: custom-operator
          image: edcelvista/ubuntu24-network-tools:v13-k8s-crd
          imagePullPolicy: Always
          command: ["app-linux"]
          resources: 
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: operator-cm
          volumeMounts:
          - name: config-volume
            mountPath: "/opt/config"
            readOnly: true
          - name: localtime
            mountPath: /etc/localtime
      volumes:
        - name: config-volume
          configMap:
            name: kubeconfig
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always