apiVersion: "k8s.edcelvista.com/v1"
kind: MyApp
metadata:
  name: myapp-resource
  namespace: demo
spec:
  image: edcelvista/ubuntu24-network-tools:v11-k8s-crd
  replicas: 1
  appSelector: myapp-resource