apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
    - name: webport
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: webhook-operator
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
