apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-always-allow
webhooks:
  - name: validating-always-allow.edcelvista.com
    rules:
      - apiGroups:
        - ''
        apiVersions:
        - 'v1'
        operations:
        - CREATE
        resources:
        - 'pods'
        scope: 'Namespaced'
    clientConfig:
      # url: https://webhook.custom-webhook.svc.cluster.local/webhook/validating/always-allow
      service:
        name: webhook
        namespace: custom-webhook
        path: "/webhook/validating/always-allow"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lVYWUyRjZCTFllVzgyL2FJRmNyYXBUZjVveUZZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXdIaGNOTWpVdwpOREkxTVRNME5UUTBXaGNOTWpVd05USTFNVE0wTlRRMFdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbU4xCmMzUnZiUzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU1MSi9YeFM4Tk5jc0ExR3o0YVU3dkIyRGxlaE5MNldGTTRjcXhkSjRZbFJ2Qnd4S3VvN29tSXJJMy9JU3NVbAo4MHVzb1FvcmdRMzRKMWk5djc1dENXczJHSEpjWmZ5bnkxUU4zc1FrUnZqVEFweVJ5aWRUS3dYTHJSWjZ4NzFBCmpwZFY1di9QZ1YycVp6ZjVDYlVLSUprQWZTUEpOZ1Nzb1VUYVc2dGJ2dHFTY1kxK0NiVFpkQzVqUTlkNmVFanYKYU1sdGVheXhkeWxQUFpVUzBWbjM2M1NlTUhGUGZ1Zyt4R25OcWRuVXZtaEQ2L1plZEZKK3FtK2k2Nkp0VnYxUQpJWloyUkQzNFkvVExDcDhjS2tMa0UxM3cyUXBBWGhTNWVEQ2t0Mmc1UjFUNS9CTkR1ejhWUTY2dU4wMG9SaTZ1CnNEejdDRHl2N2VYN3lnTjYzL1dDUmRNQ0F3RUFBYU5nTUY0d1BRWURWUjBSQkRZd05JSWFkMlZpYUc5dmF5NWoKZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU9DRm5kbFltaHZiMnN1WTNWemRHOXRMWGRsWW1odmIyc3dIUVlEVlIwTwpCQllFRkMwWGpRNUNUamdyc0ZiQUtEQ3A3T014bEpibU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU80dWplCnRnTnZoSjhaSEdvVlFpbnVYSVUrRml2ZXhPWW5XYTBqRU9CYStVVGRjbFZDVHF1elBjcmh6VFB6cmpCOTR0WVgKRkVXeWNCTXVuZ3p1TEh4WjN6OTkyaTdRRVZyMGlkSnNCYTB4bm5BOGo2Z2d0aE9UOElkUWFVNFhpQmhtQzdVQQpFZUxCOGVJYWovTGhlTmVYd21XME5uTzJNMnRtajRoUjhmTE50VC8ydHQ1WWVxYUV2R1Bhb0FHV1krL3BQSDJtClUrRFlKU2xWQzRhcGdJYUV0dnlRRFpiUi85WnZlbzFRaE92MThhVFFoM1krMXFEMnhQSTBuOThhb0RQNFRpWGsKdE0vTWVzTWFob2w2cGcvT2svK1JHN2hnYXpiZEx1eU9RbnhiMEFJQm8wRFo1MVFOakptS2llNlpPT2lYZlk5cAppNjd0TU42ZThmNUwyZE1iCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    # failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: custom-webhook.edcelvista.com/validate-always-allow
        operator: Exists
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-always-allow
webhooks:
  - name: mutating-always-allow.edcelvista.com
    rules:
      - apiGroups:
        - ''
        apiVersions:
        - 'v1'
        operations:
        - CREATE
        resources:
        - 'pods'
        scope: 'Namespaced'
    clientConfig:
      service:
        name: webhook
        namespace: custom-webhook
        path: /webhook/mutating/always-allow
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lVYWUyRjZCTFllVzgyL2FJRmNyYXBUZjVveUZZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXdIaGNOTWpVdwpOREkxTVRNME5UUTBXaGNOTWpVd05USTFNVE0wTlRRMFdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbU4xCmMzUnZiUzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU1MSi9YeFM4Tk5jc0ExR3o0YVU3dkIyRGxlaE5MNldGTTRjcXhkSjRZbFJ2Qnd4S3VvN29tSXJJMy9JU3NVbAo4MHVzb1FvcmdRMzRKMWk5djc1dENXczJHSEpjWmZ5bnkxUU4zc1FrUnZqVEFweVJ5aWRUS3dYTHJSWjZ4NzFBCmpwZFY1di9QZ1YycVp6ZjVDYlVLSUprQWZTUEpOZ1Nzb1VUYVc2dGJ2dHFTY1kxK0NiVFpkQzVqUTlkNmVFanYKYU1sdGVheXhkeWxQUFpVUzBWbjM2M1NlTUhGUGZ1Zyt4R25OcWRuVXZtaEQ2L1plZEZKK3FtK2k2Nkp0VnYxUQpJWloyUkQzNFkvVExDcDhjS2tMa0UxM3cyUXBBWGhTNWVEQ2t0Mmc1UjFUNS9CTkR1ejhWUTY2dU4wMG9SaTZ1CnNEejdDRHl2N2VYN3lnTjYzL1dDUmRNQ0F3RUFBYU5nTUY0d1BRWURWUjBSQkRZd05JSWFkMlZpYUc5dmF5NWoKZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU9DRm5kbFltaHZiMnN1WTNWemRHOXRMWGRsWW1odmIyc3dIUVlEVlIwTwpCQllFRkMwWGpRNUNUamdyc0ZiQUtEQ3A3T014bEpibU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU80dWplCnRnTnZoSjhaSEdvVlFpbnVYSVUrRml2ZXhPWW5XYTBqRU9CYStVVGRjbFZDVHF1elBjcmh6VFB6cmpCOTR0WVgKRkVXeWNCTXVuZ3p1TEh4WjN6OTkyaTdRRVZyMGlkSnNCYTB4bm5BOGo2Z2d0aE9UOElkUWFVNFhpQmhtQzdVQQpFZUxCOGVJYWovTGhlTmVYd21XME5uTzJNMnRtajRoUjhmTE50VC8ydHQ1WWVxYUV2R1Bhb0FHV1krL3BQSDJtClUrRFlKU2xWQzRhcGdJYUV0dnlRRFpiUi85WnZlbzFRaE92MThhVFFoM1krMXFEMnhQSTBuOThhb0RQNFRpWGsKdE0vTWVzTWFob2w2cGcvT2svK1JHN2hnYXpiZEx1eU9RbnhiMEFJQm8wRFo1MVFOakptS2llNlpPT2lYZlk5cAppNjd0TU42ZThmNUwyZE1iCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    # failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: custom-webhook.edcelvista.com/mutate-always-allow
        operator: Exists
    timeoutSeconds: 5