apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-pod
webhooks:
  - name: validating-pod.edcelvista.com
    rules:
      - apiGroups:
        - ''
        apiVersions:
        - 'v1'
        operations:
        - CREATE
        resources:
        - 'pods'
        scope: 'Namespaced'
    clientConfig:
      # url: https://webhook.custom-webhook.svc.cluster.local/webhook/validating/pod
      service:
        name: webhook
        namespace: custom-webhook
        path: "/webhook/validating/pod"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lVSHRJd2lDaFA1RWEvNzJqN1ZHQ2R5RkxzQ204d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXdIaGNOTWpVdwpOakF5TVRFeE1qVTVXaGNOTWpVd056QXlNVEV4TWpVNVdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbU4xCmMzUnZiUzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUpkRTYyb0FhZjhjQmwxakxpaUpuRkR6eVozQ2dRTDlaTE13bGFSWXcxZjhTSkd5ZDZ3aVdQdjNxb1dRcitPeQo4bHJwS051bzQ3NG8vQ1hMblFPOEd4TUdoZlZiRWxEVHpiaHZTdnpsTXltSU5aTUZaUXNPdnBsL3dIOTJTY05FCnFhV2d4L2hHYUJJcmw4RE9ZUmxpcmJlL0VqUlRpRk9wMzdVcmM5a1BxcDE0VGhaeGZ5akFKRGVqenF5MG5RYUwKcXJCQ3NXZndHclZWVWFNbExDQmZFSUdnbnZqVGp5NjBkNTNCQlpnRTlkUFJRODJKTEM3OUhxbXJwalBsSVMybApGZXBIRUYyaHZ6d2NBM3lmWlJ1NnllY1krTGMwbC9Zem4xcTZMbHhVNzVmeEtIVFJURGtzT2Zwa2VlNG1GWjZ3CkZuSWVQRWNrOG5WRXcvZWVnME9RVzdFQ0F3RUFBYU5nTUY0d1BRWURWUjBSQkRZd05JSWFkMlZpYUc5dmF5NWoKZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU9DRm5kbFltaHZiMnN1WTNWemRHOXRMWGRsWW1odmIyc3dIUVlEVlIwTwpCQllFRkRLdWlPbVBkYW4ydE9UaTBuRDdUdnRMRk0ybU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkRXUndHCnZJUTI3RzRzeEtEejlmYnBEUnVJV0dTRTN0YkF1ZTNRUWg1QWZraFJvdGp5d2pKaGN4Tk1IU2dlTE1nSVptY0MKdE9Vc09QZVlHeWdnWnVPc0xldHFNSmx5NGtCM0s3d3FNYjdXTDI0NUg0L0xjMUNCL3Y0ejVxSjZScWwyNzRNcAoxR0g3bHJMMHZiMExrNVI5Y2hIazVxdVVpNGFDRWJGRDZXL3dUcERaZVJ2SWsxalo5VWQ3TmpxWFE4cFgxU0xuCmZpV2FPTFZ4TnIrMmV1eUVxenFLeUFqNlY2bHRjczhUOU0vS2JRd0J2bWdFemVXZ21rVWhEWDFyNlVpUVFuZ0YKL0UwMk5OKyt2TkJYR2tHMzJlM3hWaHh5cFNDMmdzbGU0Ti82RjlNZFFMRm1VRGhKSHVvYWxVZHVid1pENlJQUQpBeitNaWh1bmREQlp0THBLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    # failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: custom-webhook.edcelvista.com/validate-pod
        operator: Exists
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-pod
webhooks:
  - name: mutating-pod.edcelvista.com
    rules:
      - apiGroups:
        - ''
        apiVersions:
        - 'v1'
        operations:
        - CREATE
        resources:
        - 'pods'
        scope: 'Namespaced'
    clientConfig:
      service:
        name: webhook
        namespace: custom-webhook
        path: /webhook/mutating/pod
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lVSHRJd2lDaFA1RWEvNzJqN1ZHQ2R5RkxzQ204d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXdIaGNOTWpVdwpOakF5TVRFeE1qVTVXaGNOTWpVd056QXlNVEV4TWpVNVdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbU4xCmMzUnZiUzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUpkRTYyb0FhZjhjQmwxakxpaUpuRkR6eVozQ2dRTDlaTE13bGFSWXcxZjhTSkd5ZDZ3aVdQdjNxb1dRcitPeQo4bHJwS051bzQ3NG8vQ1hMblFPOEd4TUdoZlZiRWxEVHpiaHZTdnpsTXltSU5aTUZaUXNPdnBsL3dIOTJTY05FCnFhV2d4L2hHYUJJcmw4RE9ZUmxpcmJlL0VqUlRpRk9wMzdVcmM5a1BxcDE0VGhaeGZ5akFKRGVqenF5MG5RYUwKcXJCQ3NXZndHclZWVWFNbExDQmZFSUdnbnZqVGp5NjBkNTNCQlpnRTlkUFJRODJKTEM3OUhxbXJwalBsSVMybApGZXBIRUYyaHZ6d2NBM3lmWlJ1NnllY1krTGMwbC9Zem4xcTZMbHhVNzVmeEtIVFJURGtzT2Zwa2VlNG1GWjZ3CkZuSWVQRWNrOG5WRXcvZWVnME9RVzdFQ0F3RUFBYU5nTUY0d1BRWURWUjBSQkRZd05JSWFkMlZpYUc5dmF5NWoKZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU9DRm5kbFltaHZiMnN1WTNWemRHOXRMWGRsWW1odmIyc3dIUVlEVlIwTwpCQllFRkRLdWlPbVBkYW4ydE9UaTBuRDdUdnRMRk0ybU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkRXUndHCnZJUTI3RzRzeEtEejlmYnBEUnVJV0dTRTN0YkF1ZTNRUWg1QWZraFJvdGp5d2pKaGN4Tk1IU2dlTE1nSVptY0MKdE9Vc09QZVlHeWdnWnVPc0xldHFNSmx5NGtCM0s3d3FNYjdXTDI0NUg0L0xjMUNCL3Y0ejVxSjZScWwyNzRNcAoxR0g3bHJMMHZiMExrNVI5Y2hIazVxdVVpNGFDRWJGRDZXL3dUcERaZVJ2SWsxalo5VWQ3TmpxWFE4cFgxU0xuCmZpV2FPTFZ4TnIrMmV1eUVxenFLeUFqNlY2bHRjczhUOU0vS2JRd0J2bWdFemVXZ21rVWhEWDFyNlVpUVFuZ0YKL0UwMk5OKyt2TkJYR2tHMzJlM3hWaHh5cFNDMmdzbGU0Ti82RjlNZFFMRm1VRGhKSHVvYWxVZHVid1pENlJQUQpBeitNaWh1bmREQlp0THBLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    # failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: custom-webhook.edcelvista.com/mutate-pod
        operator: Exists
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-tenant
webhooks:
  - name: validating-tenant.edcelvista.com
    rules:
      - apiGroups:
        - 'capsule.clastix.io'
        apiVersions:
        - 'v1beta2'
        operations:
        - UPDATE
        resources:
        - 'tenants'
        scope: 'Cluster'
    clientConfig:
      # url: https://webhook.custom-webhook.svc.cluster.local/webhook/validating/tenant
      service:
        name: webhook
        namespace: custom-webhook
        path: "/webhook/validating/tenant"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lVSHRJd2lDaFA1RWEvNzJqN1ZHQ2R5RkxzQ204d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXdIaGNOTWpVdwpOakF5TVRFeE1qVTVXaGNOTWpVd056QXlNVEV4TWpVNVdqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbU4xCmMzUnZiUzEzWldKb2IyOXJMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUpkRTYyb0FhZjhjQmwxakxpaUpuRkR6eVozQ2dRTDlaTE13bGFSWXcxZjhTSkd5ZDZ3aVdQdjNxb1dRcitPeQo4bHJwS051bzQ3NG8vQ1hMblFPOEd4TUdoZlZiRWxEVHpiaHZTdnpsTXltSU5aTUZaUXNPdnBsL3dIOTJTY05FCnFhV2d4L2hHYUJJcmw4RE9ZUmxpcmJlL0VqUlRpRk9wMzdVcmM5a1BxcDE0VGhaeGZ5akFKRGVqenF5MG5RYUwKcXJCQ3NXZndHclZWVWFNbExDQmZFSUdnbnZqVGp5NjBkNTNCQlpnRTlkUFJRODJKTEM3OUhxbXJwalBsSVMybApGZXBIRUYyaHZ6d2NBM3lmWlJ1NnllY1krTGMwbC9Zem4xcTZMbHhVNzVmeEtIVFJURGtzT2Zwa2VlNG1GWjZ3CkZuSWVQRWNrOG5WRXcvZWVnME9RVzdFQ0F3RUFBYU5nTUY0d1BRWURWUjBSQkRZd05JSWFkMlZpYUc5dmF5NWoKZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU9DRm5kbFltaHZiMnN1WTNWemRHOXRMWGRsWW1odmIyc3dIUVlEVlIwTwpCQllFRkRLdWlPbVBkYW4ydE9UaTBuRDdUdnRMRk0ybU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkRXUndHCnZJUTI3RzRzeEtEejlmYnBEUnVJV0dTRTN0YkF1ZTNRUWg1QWZraFJvdGp5d2pKaGN4Tk1IU2dlTE1nSVptY0MKdE9Vc09QZVlHeWdnWnVPc0xldHFNSmx5NGtCM0s3d3FNYjdXTDI0NUg0L0xjMUNCL3Y0ejVxSjZScWwyNzRNcAoxR0g3bHJMMHZiMExrNVI5Y2hIazVxdVVpNGFDRWJGRDZXL3dUcERaZVJ2SWsxalo5VWQ3TmpxWFE4cFgxU0xuCmZpV2FPTFZ4TnIrMmV1eUVxenFLeUFqNlY2bHRjczhUOU0vS2JRd0J2bWdFemVXZ21rVWhEWDFyNlVpUVFuZ0YKL0UwMk5OKyt2TkJYR2tHMzJlM3hWaHh5cFNDMmdzbGU0Ti82RjlNZFFMRm1VRGhKSHVvYWxVZHVid1pENlJQUQpBeitNaWh1bmREQlp0THBLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    # failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: custom-webhook.edcelvista.com/tenant
        operator: Exists
    timeoutSeconds: 5