apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-always-allow
webhooks:
  - name: validating-always-allow.edcelvista.com
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      # url: https://webhook.custom-webhook.svc.cluster.local/webhook/validating/always-allow
      service:
        name: webhook
        namespace: custom-webhook
        path: "/webhook/validating/always-allow"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWVENDQWoyZ0F3SUJBZ0lVZmNaOXdjNDhaNnBwMUx4S0MxRkdjdFlGWGVBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09qRWRNQnNHQTFVRUF3d1VLaTVqZFhOMGIyMHRkMlZpYUc5dmF5NXpkbU14R1RBWEJnTlZCQW9NRUdWawpZMlZzZG1semRHRmtiM1JqYjIwd0hoY05NalV3TkRJMU1USTBNekEwV2hjTk1qWXdOREkxTVRJME16QTBXakE2Ck1SMHdHd1lEVlFRRERCUXFMbU4xYzNSdmJTMTNaV0pvYjI5ckxuTjJZekVaTUJjR0ExVUVDZ3dRWldSalpXeDIKYVhOMFlXUnZkR052YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFRXdkVFQgoveTZUL0hqbkU3WlliZWpvalZJNTcrdDFzaDBhaGd2cG0yODhDTUVyNFhrSEtjdFMycTB5UHdSNXpRLzg4NU9HCm1kWExPTjZqOFQ0STVUdE9NODFWTzhGTk1na2VTR0lQV2s2eW1VanN3bEF2N2dEblFvR2JRQjhQVEVqV1ljVWgKNDRDUzd5cWdRcmVNWTYwSnJNd2hINW5nSEY4bTZmMThqUVVOVS8vbUFmQVhnb212am14bm1JdUg2aHlGT1FOVApvZmhRSXRsMURxUFo2YUNseEFrQjlQTjR1SVBwVWluNk94N2dVNXh0aTEyUEt5RjY0cElNMG8veEk0SGRaQlFHCmRuTTNlYjMxZzl4RWpPZ295aDhrWGIvNkR2eDhtOHdtbWNndm5sSmJMR2NQTUNkcG1rRi9PMGx3MHdWSXBiakcKWWp1RHhrNkFQOHlhQzgwQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZENFF4eG5CS2ZkUFdHWDZRZ2lIaDFzMApNMWVkTUI4R0ExVWRJd1FZTUJhQUZENFF4eG5CS2ZkUFdHWDZRZ2lIaDFzME0xZWRNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVoTVJKZ1YzaC9QU0NRajdkT1FaeGk2WDlLSUgwWEUKRFJxblEyZU5tait2UndCVGM4amViMmxhSjZCVmNQZUUxSVAvVVpaOC9VY1pBVStGQ2owN0R4QnFacWtGbWpXeQpyb2dJL29ZLzloTzdZaHB3amRQTitBREd1L3JKZjJCbHEwMmo2RHkxdGNiWVB1bEptOHpOT0ovYmtqSElWcDUyCkZJSEorQjBrTXBvZGpVUmcrOFQybVA1UFJzMDI1anpHRHRGbTNTTHJUS3AzMytrR2diNDJtRzVzVUd6ejJTTVoKK3JaK2RNcHgxcUNlOTB2UGtjbUpSYnNLa2d6L2Y1cHB4bTlCYTVkcGRwaHBCdmpDcFVIQUxONTNTRkhLNXovSgp6ckhWRnE1SkQ4aHhqaEJvcGVvcVlQK0ZKMDhJQ0dqSnBPdTd6T0JaWFFpUTFtTThYLzFxVWtZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None