apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-always-allow
webhooks:
  - name: validating-always-allow.edcelvista.com
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      # url: https://webhook.custom-webhook.svc.cluster.local/webhook/validating/always-allow
      service:
        name: webhook
        namespace: custom-webhook
        path: "/webhook/validating/always-allow"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZVENDQWttZ0F3SUJBZ0lVWXZNbnI0V1RIWGFSR1FUVCs3WVZMWGFXSEI4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NWpkWE4wYjIwdGQyVmlhRzl2YXk1emRtTXhHVEFYQmdOVgpCQW9NRUdWa1kyVnNkbWx6ZEdGa2IzUmpiMjB3SGhjTk1qVXdOREkxTVRJek5qVTVXaGNOTWpZd05ESTFNVEl6Ck5qVTVXakJBTVNNd0lRWURWUVFEREJwM1pXSm9iMjlyTG1OMWMzUnZiUzEzWldKb2IyOXJMbk4yWXpFWk1CY0cKQTFVRUNnd1FaV1JqWld4MmFYTjBZV1J2ZEdOdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFLNXBhdmNEQ2o3bHZjMGRwcU1USGRqdzcxaUY3NVNsTG51YVFDSE9rajFhR2FzZGFWUHFuaU1BClEvZUJWNG9KT3NBc29vSldKM0ZMQ3luZlpnVE9FZnBwUTZ5K25yQTMzcmN1YXBRU01wamZzbUpnWENUY0FFbi8KcFE5U0ZWQ3V4d2g4V3BjbUM5azAxanY5VVNNaGJ0VUhPR3JtQUUxSUdSNE9pUnBmSHp5R05zdkYwcU5UWUMyRwpLT1VqcmNGRWw3TlJQcUxJeUNVZDcxc2VQRHo5ZmJhczZlRTNDVzF3QXVZUC9UbGJLOXhVWG5mRytWUWw5d2ZWCmFsN1V6NVhxdEpuOTFkUFBPdzRxWTlDL21YMXN0Y25iRTkzQm5UREFLRzNUb0I0VzFXTlp4LzkyMHpPRzlLL2QKVDltWFg3ODV1Zm5ZOU1KMW9zYzd0ZU5TZ3dCZko4MENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGS012SzRPNgpSNm1ST3ZjZXZ1QzRHU3ZmYjRWbE1COEdBMVVkSXdRWU1CYUFGS012SzRPNlI2bVJPdmNldnVDNEdTdmZiNFZsCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBYkRpdjRPV0kwQzc1ZGYKSm9ZeHRVZnJUdW5wTUZrME95WXJyNXNRWHpPN0xTem0wMDNLVEFldm9QZEp6MGdqTTY0NTZuc3NJS3RMZmhiegphT2wzM0RFWkJ6RUpVTGVVUE9waXhmbkpjVExNbmIzdmNvWWY4UTFaS1VvUTc4NytPbndDY0VjbHd6SnF3ZEsvCmpuOTVJUXRlcDd4aXFIMkhDNUZlbUpiY2F4WDJ3T05udEdLdnNTYWZNcjJ1L1RCUnVxZ3ZNSTdwUWN0Um0xM3oKb1dOSkdFT00wY0xOOG1PMDlTZTh0QVFqaUUwT05NcVdjdWdNanpETkYyUDUrQUptVnQrT1k4dW9nMDNZOXNScQpIdkw3UkZXSnFuU0VBNjM1L3hRZkZVbnZBemlVeVJSN2U2TnhFczdEVGdvNExPWiswRWFGbUNDeGJUUUZIdGNCCkwyTFBDMlU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None