apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-controller-role-st
rules:
- apiGroups: ["k8s.edcelvista.com"]
  resources: ["SecTool"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["create", "get", "update", "list", "watch", "delete"]