apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-operator
  labels:
    app: custom-operator
    env: dev
spec:
  selector:
    matchLabels:
      app: custom-operator
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: custom-operator
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  custom-operator
        image:  edcelvista/ubuntu24-network-tools:v13-k8s-crd
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["app-linux"]
        resources: 
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi