apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-operator
  labels:
    app: custom-operator
    env: dev
spec:
  selector:
    matchLabels:
      app: custom-operator
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: custom-operator
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
        - name:  custom-operator
          image:  edcelvista/ubuntu24-network-tools:v18-k8s-crd
          imagePullPolicy: Always
          command: ["custom-operator-secret-recon-linux"]
          resources: 
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi